import 'dotenv/config'; // load .env

export const KAFKA_TOPICS = {
  CV_PARSING_REQUEST: process.env.KAFKA_CV_PARSING_REQUEST || '',
  CV_PARSING_REQUEST_DLQ: process.env.KAFKA_CV_PARSING_REQUEST_DLQ || '',
  CV_MATCHING_REQUEST: process.env.KAFKA_CV_MATCHING_REQUEST || '',
  CV_MATCHING_REQUEST_DLQ: process.env.KAFKA_CV_MATCHING_REQUEST_DLQ || '',
  JD_SKILL_EXTRACTION_REQUEST:
    process.env.KAFKA_JD_SKILL_EXTRACTION_REQUEST || '',
  JD_SKILL_EXTRACTION_REQUEST_DLQ:
    process.env.KAFKA_JD_SKILL_EXTRACTION_REQUEST_DLQ || '',
} as const;

export const KAFKA_DLQ_MAP: Record<string, string> = {
  [KAFKA_TOPICS.CV_PARSING_REQUEST]: KAFKA_TOPICS.CV_PARSING_REQUEST_DLQ,
  [KAFKA_TOPICS.CV_MATCHING_REQUEST]: KAFKA_TOPICS.CV_MATCHING_REQUEST_DLQ,
  [KAFKA_TOPICS.JD_SKILL_EXTRACTION_REQUEST]:
    KAFKA_TOPICS.JD_SKILL_EXTRACTION_REQUEST_DLQ,
};
