import { MigrationInterface, QueryRunner } from 'typeorm';

export class AddCandidateCvEntity1776500000000 implements MigrationInterface {
  name = 'AddCandidateCvEntity1776500000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    // ===== Step 1: Clean existing dev data =====
    // Delete in correct FK order to avoid constraint violations
    await queryRunner.query(`DELETE FROM "EntitySkills" WHERE "candidateId" IS NOT NULL`);
    await queryRunner.query(`DELETE FROM "Applications"`);
    await queryRunner.query(`DELETE FROM "Candidates"`);

    // ===== Step 2: Create CandidateCvs table =====
    await queryRunner.query(`
      CREATE TYPE "public"."CandidateCvs_parsingstatus_enum" AS ENUM('PENDING', 'SUCCESS', 'FAILED')
    `);

    await queryRunner.query(`
      CREATE TABLE "CandidateCvs" (
        "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
        "createDate" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        "updateDate" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        "candidateId" uuid,
        "storageKey" character varying NOT NULL,
        "contentHash" character varying(64) NOT NULL,
        "rawCvText" text,
        "cvEmbedding" jsonb,
        "summary" text,
        "metadata" jsonb,
        "parsedJson" jsonb,
        "parsingStatus" "public"."CandidateCvs_parsingstatus_enum" NOT NULL DEFAULT 'PENDING',
        CONSTRAINT "PK_CandidateCvs" PRIMARY KEY ("id"),
        CONSTRAINT "UQ_CandidateCvs_candidate_hash" UNIQUE ("candidateId", "contentHash")
      )
    `);

    await queryRunner.query(`
      ALTER TABLE "CandidateCvs"
      ADD CONSTRAINT "FK_CandidateCvs_candidateId"
      FOREIGN KEY ("candidateId") REFERENCES "Candidates"("id")
      ON DELETE CASCADE ON UPDATE NO ACTION
    `);

    // ===== Step 3: Add candidateCvId to Applications =====
    await queryRunner.query(`
      ALTER TABLE "Applications"
      ADD "candidateCvId" uuid
    `);

    await queryRunner.query(`
      ALTER TABLE "Applications"
      ADD CONSTRAINT "FK_Applications_candidateCvId"
      FOREIGN KEY ("candidateCvId") REFERENCES "CandidateCvs"("id")
      ON DELETE SET NULL ON UPDATE NO ACTION
    `);

    // ===== Step 4: Change EntitySkills FK from candidateId to candidateCvId =====
    // Drop old FK constraint (name may vary, drop by column)
    await queryRunner.query(`
      ALTER TABLE "EntitySkills"
      DROP CONSTRAINT IF EXISTS "FK_EntitySkills_candidateId"
    `);

    // Try alternative constraint names generated by TypeORM
    await queryRunner.query(`
      DO $$
      DECLARE
        r RECORD;
      BEGIN
        FOR r IN (
          SELECT constraint_name
          FROM information_schema.table_constraints
          WHERE table_name = 'EntitySkills'
            AND constraint_type = 'FOREIGN KEY'
            AND constraint_name LIKE '%candidate%'
        ) LOOP
          EXECUTE 'ALTER TABLE "EntitySkills" DROP CONSTRAINT "' || r.constraint_name || '"';
        END LOOP;
      END $$;
    `);

    // Drop the old candidateId column
    await queryRunner.query(`
      ALTER TABLE "EntitySkills"
      DROP COLUMN IF EXISTS "candidateId"
    `);

    // Add the new candidateCvId column
    await queryRunner.query(`
      ALTER TABLE "EntitySkills"
      ADD "candidateCvId" uuid
    `);

    await queryRunner.query(`
      ALTER TABLE "EntitySkills"
      ADD CONSTRAINT "FK_EntitySkills_candidateCvId"
      FOREIGN KEY ("candidateCvId") REFERENCES "CandidateCvs"("id")
      ON DELETE CASCADE ON UPDATE NO ACTION
    `);

    // ===== Step 5: Change experienceYears from int to decimal =====
    await queryRunner.query(`
      ALTER TABLE "EntitySkills"
      ALTER COLUMN "experienceYears" TYPE numeric(4,1)
    `);

    // ===== Step 6: Drop old columns from Candidates =====
    await queryRunner.query(`ALTER TABLE "Candidates" DROP COLUMN IF EXISTS "rawCvText"`);
    await queryRunner.query(`ALTER TABLE "Candidates" DROP COLUMN IF EXISTS "summary"`);
    await queryRunner.query(`ALTER TABLE "Candidates" DROP COLUMN IF EXISTS "cvFileUrl"`);
    await queryRunner.query(`ALTER TABLE "Candidates" DROP COLUMN IF EXISTS "storageKey"`);
    await queryRunner.query(`ALTER TABLE "Candidates" DROP COLUMN IF EXISTS "cvEmbedding"`);
    await queryRunner.query(`ALTER TABLE "Candidates" DROP COLUMN IF EXISTS "metadata"`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // Restore Candidates columns
    await queryRunner.query(`ALTER TABLE "Candidates" ADD "rawCvText" text`);
    await queryRunner.query(`ALTER TABLE "Candidates" ADD "summary" text`);
    await queryRunner.query(`ALTER TABLE "Candidates" ADD "cvFileUrl" character varying`);
    await queryRunner.query(`ALTER TABLE "Candidates" ADD "storageKey" character varying`);
    await queryRunner.query(`ALTER TABLE "Candidates" ADD "cvEmbedding" jsonb`);
    await queryRunner.query(`ALTER TABLE "Candidates" ADD "metadata" jsonb`);

    // Restore EntitySkills.candidateId
    await queryRunner.query(`ALTER TABLE "EntitySkills" DROP CONSTRAINT IF EXISTS "FK_EntitySkills_candidateCvId"`);
    await queryRunner.query(`ALTER TABLE "EntitySkills" DROP COLUMN IF EXISTS "candidateCvId"`);
    await queryRunner.query(`ALTER TABLE "EntitySkills" ADD "candidateId" uuid`);
    await queryRunner.query(`ALTER TABLE "EntitySkills" ALTER COLUMN "experienceYears" TYPE integer`);

    // Drop candidateCvId from Applications
    await queryRunner.query(`ALTER TABLE "Applications" DROP CONSTRAINT IF EXISTS "FK_Applications_candidateCvId"`);
    await queryRunner.query(`ALTER TABLE "Applications" DROP COLUMN IF EXISTS "candidateCvId"`);

    // Drop CandidateCvs table
    await queryRunner.query(`ALTER TABLE "CandidateCvs" DROP CONSTRAINT IF EXISTS "FK_CandidateCvs_candidateId"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "CandidateCvs"`);
    await queryRunner.query(`DROP TYPE IF EXISTS "public"."CandidateCvs_parsingstatus_enum"`);
  }
}
